-- MySQL Script generated by MySQL Workbench
-- 2019年03月19日 星期二 20时14分35秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Pihealth
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Pihealth
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pihealth` DEFAULT CHARACTER SET utf8 ;
USE `Pihealth` ;

-- -----------------------------------------------------
-- Table `Pihealth`.`warning_events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pihealth`.`warning_events` (
  `wid` INT NOT NULL,
  `wtime` DATETIME NOT NULL,
  `wip` VARCHAR(20) NOT NULL,
  `wtype` INT(5) NOT NULL,
  `wdetails` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`wid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pihealth`.`types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pihealth`.`types` (
  `tid` INT NOT NULL,
  `tname` CHAR(20) NOT NULL,
  PRIMARY KEY (`tid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pihealth`.`notes_events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pihealth`.`notes_events` (
  `nid` INT NOT NULL,
  `ntime` DATETIME NOT NULL,
  `nip` VARCHAR(20) NOT NULL,
  `ntypes` INT NOT NULL,
  `ndetails` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`nid`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
